defaultPortal: Nick
portals:
  - name: Nick
    portalId: 26595626
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CISo1ILfMRILAA0AAAAA4A0DQAIYqqLXDCDonSMo7ukMMhQf1lQAvW6cIIRhEo5ZbdCUIsoCdzpAAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwCO8DE8AAAGAEQAYAAAAAAAAAAAAAAAAAAwAgAAAAAAAAAADEIU7jDHQDYQs82pP3aInVVBF5YbrOtKA2V1MVIAWgA
        expiresAt: '2024-02-28T15:28:44.060Z'
    accountType: STANDARD
    personalAccessKey: >-
      CiRldTEtMDRiNC1lOGNlLTQ4OWQtOTVmOC02ODE2YTM1MGM0ZTUQqqLXDBjonSMqGQAF5pGCPXF75spWB833p9fIl5mHAi5NMzNKA2V1MQ
    sandboxAccountType: null
